name: 'Issue logfmt patcher'
icon: align-left
color: purple
description: 'Finds logfmt log lines in issues and replaces them with formatted version that is easier to follow'
inputs:
  repo-token:
    description: 'The PAT to use for authorizing the edits'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
