on: 
  issues:
    types: [opened, reopened]

jobs:
  patch_issue:
    runs-on: ubuntu-latest
    name: Patch Issue (Private)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        uses: ./
        id: logfmt-patcher
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
